spring:
  datasource:
    url: jdbc:mysql://resume-db.cq0kh8e6xcju.ap-northeast-1.rds.amazonaws.com:3306/resume?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: # fixme
    password: # fixme

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false