spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: # fixme
    password: # fixme

resume:
  mail:
    frontend-host: http://localhost:9000/