spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: root

resume:
  mail:
    frontend-host: http://localhost:9000

server:
  port: 8080

#debug: true