spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: ENC(w0roBx8WVqCLO6hP7CucpbqqhF+pvntsaYpCQY+rplSK1lBg7737RsJ3RF6QSdwQ)