spring:
  datasource:
    url: jdbc:mysql://resumedb.clbhgo50wgcs.ap-northeast-1.rds.amazonaws.com:3306/resume?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: ENC(bN3Zm+Bhq45l6zCZij1d743Svm/rwie7OvrJSasMxc1IkZBlB4cgx/dEi7Cf8Mnl)

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false